subtitle = "JConf Mexico 2025"
# text_color = ""
author = "JConf Mexico"
# favicon = ""
site_logo = "/img/logo_orange.png"
description = "The all JVM biggest conference... IN MEXICO"
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-navy"
# choose fitting and alignment styles for the featured image using Tachyons classes such as "cover|contain" for fitting and "bg-top|bg-center|bg-bottom" for alignment, or add any other class space-separated to customize further
featured_image_class = "cover bg-top"
# choose a color dimming class for the page or site header from any on this page: https://tachyons.io/docs/themes/skins/, preface it with "bg-" and add the value such as "-X0" where X is in [1,9]
cover_dimming_class = "bg-black-60"
# recent_posts_number = 3

[contact]
email = "jconfmex@gmail.com"

[ananke.social]
[ananke.social.share]
networks = ["email", "x-twitter", "facebook", "linkedin"]

[ananke.social.follow]
networks = ["github", "x-twitter", "facebook", "linkedin"]

[ananke.social.github]
username = "JConfMexico"

[ananke.social.x-twitter]
username = "jconfmexico"
[ananke.social.facebook]
username = "JConfMexico"
profilelink = "https://www.facebook.com/JConfMexico"

[ananke.social.linkedin]
profilelink = "https://www.linkedin.com/company/jconfmexico"
