subtitle = "JConf Mexico 2025"
author = "JConf Mexico"
site_logo = "/img/logo_orange.png"
description = "The all JVM biggest conference... IN MEXICO"
background_color_class = "bg-navy"
featured_image_class = "cover bg-top"
cover_dimming_class = "bg-black-60"

eventDate = "June 7th, 2025"
eventAddress = "Av. Gral Ramón Corona No 2514"
eventLocation = "Colonia Nuevo México, 45201 Zapopan, Jal., Mexico"
homeTitle = "JConf Mexico: Building Together"
homeSubtitle = "A Java Community Conference"
homeTagline = "by Communities for Communities"
homeDescription = "Join us for a friendly gathering of Java enthusiasts where everyone learns from each other. Share knowledge, discover new possibilities, and connect with fellow developers in an inclusive space that celebrates our growing Mexican Java community."

[contact]
email = "jconfmex@gmail.com"

[ananke.social]
[ananke.social.share]
networks = ["email", "x-twitter", "facebook", "linkedin"]

[ananke.social.follow]
networks = ["github", "x-twitter", "facebook", "linkedin"]

[ananke.social.github]
username = "JConfMexico"

[ananke.social.x-twitter]
username = "jconfmexico"

[ananke.social.facebook]
username = "JConfMexico"
profilelink = "https://www.facebook.com/JConfMexico"

[ananke.social.linkedin]
profilelink = "https://www.linkedin.com/company/jconfmexico"